# Generated by Django 5.2 on 2025-04-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quest",
            old_name="is_activate",
            new_name="is_active",
        ),
    ]
