services:
  - type: web
    name: me-tycoon-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn me_tycoon_backend.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: me-tycoon-db
          property: connectionString

databases:
  - name: me-tycoon-db
    databaseName: metycoon
    user: metycoon_user